version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    environment:
      - DB_HOST=database
      - DB_DATABASE=batchbox
      - DB_USERNAME=root
      - DB_PASSWORD=Stark@321
    depends_on:
      - database

  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Stark@321
      - MYSQL_DATABASE=batchbox
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: